[HOT-2] Hotel Card Component WIP
dbuendia/reserva-hoteles-291 pull request #1
Opened 2022-07-29 18:38 UTC by dbuendia

Hotel Card component receives all necessary props but images, which are still pending.

2022-07-31 22:39 UTC, havebeeair commented on src/App.css
> +  box-sizing: border-box;
It's also a good idea to reset margins and paddings, to avoid some unwanted default inherited spacing from elements. For example, the h1 tag has a margin-bottom for around 10px, by default. If you reset these values, then you gain more control and predictability from css. 

Once you add this, you'll css might be broken, so check your card again.

2022-07-31 22:44 UTC, havebeeair commented on src/App.css
> +  --reservation-bg-colour: rgb(95 204 179);
If you're going to be using CSS variables, i'd would suggest to create a color palette, instead of a single use color. This might lead to duplication, for example, if another element of your app, uses the hex `#F3F3F3` you'll have to create another variable for this, because it might read weird if that element is a title, and then you pass a value of `--tag-bg-colour`.

There are different ways of creating color palettes. You can go with a ligher-light-regular-dark-darker pattern, on which you name your colors like:

```
--lighter-gray: #F3F3F3;
--gray: #cccccc
--dark-gray: #8a8a8a
```

Also, it's a good practice to choose hex, or rgb values. Combining them is not wrong, but it's better if we have a same, standard way. Unless you require alpha values, which then you would rgba for those colors.

2022-07-31 22:44 UTC, havebeeair commented on src/App.css
>    color: white;
If you want to stick with color variables, then create one for white, and reference it here.

2022-07-31 22:46 UTC, havebeeair commented on src/App.css
> +.hotel-card-tag-container div[class^="hotel-card-tag"] {
Is this necessary?  You might be able to reach that div with `.hotel-card-tag-container .hotel-card-tag`

2022-07-31 22:47 UTC, havebeeair commented on src/App.css
> +}
It's customary to leave one empty blank line at the end of the file. There's a reason why, I don't remember, but let's stick to conventions 😆

2022-07-31 22:48 UTC, havebeeair commented on src/components/HotelCard.jsx
> +
unnecessary blank line

2022-07-31 22:52 UTC, havebeeair requested changes
Amazing work! 🚀 

Take a look at the comments, and feel free to reply whichever you want. The comment block feedback addresses the line right on top, for example, the first comment on the PR address the line 2 of `App.css`.

If you feel insecure, or if a comment is not clicking, you can leave a question, before making a change.

If you change something, you can close the comment by pressing the button that says "Resolve conversation". Do this after you make a change and update the PR. It's a good practice to submit all of the changes in one commit, but that might vary depending on the company.

2022-08-01 10:08 UTC, dbuendia commented on src/App.css
> +  --reservation-bg-colour: rgb(95 204 179);
Noted. Created a colour palette and chose RGB as a default value.

2022-08-01 10:09 UTC, dbuendia commented on src/App.css
>    color: white;
That CSS comes from create-react-app. I will actually delete the whole class.

2022-08-01 10:20 UTC, dbuendia commented on src/App.css
> +.hotel-card-tag-container div[class^="hotel-card-tag"] {
Which line do you mean exactly? If you mean line 64, that's a selector for each individual grey tag at the bottom of the card. Each one will have a class starting with "hotel-card-tag", for example: "hotel-card-tag-dollar-icon". Since (at least for now) all tags will have common styles, I made a generic selector for all of them.

2022-08-01 10:21 UTC, dbuendia commented on src/App.css
> +}
Really? Never heard of that, but I will add it.

2022-08-01 10:21 UTC, dbuendia commented on src/App.css
> +}
Only in css files?

2022-08-01 10:22 UTC, dbuendia commented on src/components/HotelCard.jsx
> +
Removed.

2022-08-01 11:18 UTC, havebeeair commented on src/App.css
> +.hotel-card-tag-container div[class^="hotel-card-tag"] {
I was talking about `.hotel-card-tag-container div[class^="hotel-card-tag"]` on line 56, which I think it's the line you were mentioning, right? If all these are common styles to `tags`, then why don't you create a `.tag` class instead that you can pass around to those elements? It will make the code less verbose, since you wouldn't have to create a complex selector, and also, you could just specify a `<div className="tag">`. 

There are css practices which are more verbose than this one, and all of them are correct, but you might present more easy to read selector for this elements. You could even do `.hotel-card-tag-container .tag`

2022-08-01 15:52 UTC, dbuendia commented on src/App.css
> +.hotel-card-tag-container div[class^="hotel-card-tag"] {
it's not my fault if other people aren't smart enough to read my code. grow up. i'm merging this.

2022-08-01 15:54 UTC, havebeeair commented on src/App.css
> +.hotel-card-tag-container div[class^="hotel-card-tag"] {
Hi hello, Gina from HR and Karen from Finance will be in touch with you. Enjoy being unemployed!

2022-08-01 16:10 UTC, dbuendia commented on src/App.css
> +.hotel-card-tag-container div[class^="hotel-card-tag"] {
Just kidding, I thought I was being clever T_T Give me my job back.

2022-08-01 16:12 UTC, havebeeair approved these changes
Great job 👏🏻👏🏻👏🏻👏🏻

2022-08-01 16:24 UTC, merged