Added "Todos" option and Filter logic
dbuendia/reserva-hoteles-291 pull request #6
Opened 2022-08-08 13:41 UTC by dbuendia

- Added "Todos" option for all selects.
- Added filter logic (only selected elements from dataset are displayed)

<img width="1728" alt="Captura de Pantalla 2022-08-08 a las 15 40 37" src="https://user-images.githubusercontent.com/14167326/183431740-113ab60b-ee40-4fa6-85cc-8aec2a57f1ab.png">
.

2022-08-08 14:21 UTC, havebeeair requested changes

2022-08-08 14:21 UTC, havebeeair commented on src/components/Hotels.jsx
> +      {filteredHotels.map((elem) => {
Why changed to `elem`? I think `hotel` suits best.

2022-08-08 14:21 UTC, havebeeair commented on src/components/Hotels.jsx
> +        size = "Grande";
Can we reference the variables from `consts.js` instead of hardcoding?

2022-08-09 12:24 UTC, dbuendia commented on src/components/Hotels.jsx
> +      {filteredHotels.map((elem) => {
As we discussed privately, elem will remain at least for now. 👍🏻

2022-08-09 12:25 UTC, dbuendia commented on src/components/Hotels.jsx
> +        size = "Grande";
Updated!

2022-08-09 15:47 UTC, merged